allowBuilds:
  node-pty: true
minimumReleaseAgeExclude:
  - '@deepseek-ai/dsh-host-webserver@0.1.5-rc.2'
  - '@deepseek-ai/dsh-invariants@0.1.5-rc.2'
  - '@deepseek-ai/dsh-client-locale@0.1.5-rc.2'
  - '@deepseek-ai/dsh-client-ui-slots@0.1.5-rc.2'
